package com.example.sawrabin.moviebookingapp.utils

const val BASE_URL_MOVIE_BOOKING = "https://tmba.padc.com.mm"
const val BASE_URL_MOVIE = "https://api.themoviedb.org"
const val BASE_IMAGE_URL = "https://image.tmdb.org/t/p/w400/"
const val MOVIE_API_KEY = "bb2e8fd368226d797b199c34526a0477"
const val API_GET_PROFILE = "/api/v1/profile"
const val API_REGISTER = "/api/v1/register"
const val API_EMAIL_LOGIN = "/api/v1/email-login"
const val API_USER_LOGOUT = "/api/v1/logout"
const val API_GET_CINEMA_DAY_TIMESLOTS = "/api/v1/cinema-day-timeslots"
const val API_GET_SEATING_PLAN = "/api/v1/seat-plan"
const val API_GET_SNACK_LIST = "/api/v1/snacks"
const val API_GET_PAYMENT_METHODS = "/api/v1/payment-methods"
const val API_CREATE_CARD = "/api/v1/card"
const val API_CHECK_OUT="/api/v1/checkout"
const val API_GET_NOW_SHOWING = "/3/movie/now_playing"
const val API_GET_UPCOMING = "/3/movie/upcoming"
const val API_GET_MOVIE_DETAIL = "/3/movie"
const val API_GET_CREDIT = "/3/movie"
const val API_GET_IMDB = "/3/find"


//Parameter
const val PARAM_AUTHORIZATION = "Authorization"
const val PARAM_APIKEY = "api_key"
const val PARAM_NAME = "name"
const val PARAM_EMAIL = "email"
const val PARAM_PHONE = "phone"
const val PARAM_PASSWORD = "password"
const val PARAM_MOVIE_ID = "movie_id"
const val PARAM_DATE = "date"
const val PARAM_BOOKING_DATE = "booking_date"
const val PARAM_CINEMA_DAY_TIMESLOT_ID = "cinema_day_timeslot_id"
const val PARAM_EXTERNAL_SOURCE = "external_source"
const val PARAM_CARD_NUMBER="card_number"
const val PARAM_CARD_HOLDER="card_holder"
const val PARAM_EXPIRATION_DATE="expiration_date"
const val PARAM_CVC="cvc"
const val NETWORK_REQUEST_OK = 200